import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../../core/promptTypes";
import {
  type WorldImportExtractionPromptInput,
  type NovelThemeWorldGenerationPromptInput,
  type WorldStructureBackfillPromptInput,
  type WorldStructureSectionPromptInput,
  type WorldVisualizationPromptInput,
} from "../world.promptTypes";
import {
  worldImportExtractionSchema,
  novelThemeWorldGenerationSchema,
} from "../world.promptSchemas";
import { worldStructuredDataSchema, worldStructureSectionOutputSchema } from "../../../../services/world/worldSchemas";
import { worldVisualizationDraftSchema } from "../../../../services/world/worldVisualizationSchema";
import {
  buildStructureSectionInstructions,
} from "../../../../services/world/worldServiceShared";

function normalizeWorldStructureSectionPayload(
  value: z.infer<typeof worldStructureSectionOutputSchema>,
  input: WorldStructureSectionPromptInput,
): z.infer<typeof worldStructureSectionOutputSchema> {
  const arraySections = new Set(["locations"]);
  const shouldReturnArray = arraySections.has(input.section);

  if (shouldReturnArray) {
    if (!Array.isArray(value)) {
      throw new Error(`world.structure.generate 在 section=${input.section} 时必须返回数组。`);
    }
    return value;
  }

  if (!value || typeof value !== "object" || Array.isArray(value)) {
    throw new Error(`world.structure.generate 在 section=${input.section} 时必须返回对象。`);
  }
  if (input.section === "factions") {
    const record = value as Record<string, unknown>;
    if (!Array.isArray(record.factions) && !Array.isArray(record.forces)) {
      throw new Error("world.structure.generate 在 section=factions 时必须返回包含 factions 或 forces 数组的对象。");
    }
  }
  return value;
}

export const worldVisualizationPrompt: PromptAsset<
  WorldVisualizationPromptInput,
  z.infer<typeof worldVisualizationDraftSchema>
> = {
  id: "world.visualization.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldVisualizationDraftSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观可视化抽取器。",
      "你的任务是把输入中的世界设定、阵营关系、地理结构和时间演变，提炼为可直接用于可视化展示的结构化 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "factionGraph": {',
      '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
      '    "edges": [{"source":"faction-1","target":"faction-2","relation":"同盟|合作|支援|对抗|敌对|统属|压制|贸易|竞争|中立|关联"}]',
      "  },",
      '  "powerTree": [{"level":"L1","description":"..."}],',
      '  "geographyMap": {',
      '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
      '    "edges": [{"source":"geo-1","target":"geo-2","relation":"相邻|通道|隔绝|控制","routeType":"road|river|sea|portal|trade|military|border|other","distanceHint":"...","direction":"north|south|east|west|center|northeast|northwest|southeast|southwest","risk":"..."}]',
      "  },",
      '  "timeline": [{"year":"...","event":"..."}]',
      "}",
      "",
      "全局硬规则：",
      "1. 所有 label、relation、description、event、year 都必须使用简体中文。",
      "2. 只能抽取文本中明确存在或可低风险推断的信息，不得凭空编造世界结构。",
      "3. 输出目标是“可视化结构抽取”，不是世界观赏析，也不是剧情总结。",
      "4. 各部分之间必须一致，不得出现 factionGraph、geographyMap、timeline 互相打架的情况。",
      "",
      "factionGraph 规则：",
      "1. 必须优先反映真实势力关系，不要用模糊泛化关系替代明确关系。",
      "2. nodes 数量控制在 4-12 个之间，优先保留核心势力、关键种族、主要组织或国家主体。",
      "3. type 只能使用：state、faction、race、organization、other。",
      "4. edge.relation 只能使用：同盟、合作、支援、对抗、敌对、统属、压制、贸易、竞争、中立、关联。",
      "5. 不要为了凑节点而加入无叙事价值的小势力或一次性提及对象。",
      "6. 如果两个势力关系不明确，就不要强行连边。",
      "",
      "powerTree 规则：",
      "1. powerTree 用于抽取权力层级、力量阶梯、统治结构或资源支配结构。",
      "2. 每项 level 应体现层级位置，如 L1、L2、L3。",
      "3. description 必须写清这一层代表什么权力/力量层，而不是空泛写“上层”“中层”。",
      "4. 若文本没有明确力量层级，可保守提炼最稳定的层级结构，不要硬造复杂等级体系。",
      "",
      "geographyMap 规则：",
      "1. geographyMap 用于提取关键地点之间的空间位置与连通关系，而不是列地点清单。",
      "2. nodes 应优先保留对世界运行、势力分布或故事推进有意义的核心地点。",
      "3. x/y 使用 0-100 的相对地图坐标：x 越大越偏东，y 越大越偏南；中心地点约为 50/50。",
      "4. directionHint 必须与 x/y 大体一致；文本没有明确方向时，允许根据叙事层级做保守布局，但不要假装有精确距离。",
      "5. regionType 用于区分大陆、国家、区域、城市、地标、边境、路线或其他。",
      "6. edges.relation 只能使用：相邻、通道、隔绝、控制。",
      "7. routeType 用于标记道路、河流、海路、传送、商道、军道、边界或其他；没有依据时用 other。",
      "8. 不要把纯剧情场景、一次性地点或无空间结构价值的地点塞进地图。",
      "9. 若地点之间关系不明确，不要强行连边。",
      "",
      "timeline 规则：",
      "1. timeline 只提取对世界格局有影响的重要历史节点、阶段变化或关键事件。",
      "2. year 可以是具体年份，也可以是阶段性时间表达，如“旧纪元末期”“三年前”“新朝建立初期”。",
      "3. event 必须简洁写清“发生了什么变化”，不要写成长段故事。",
      "4. 不要把普通背景介绍或局部人物经历误写成世界时间线节点。",
      "",
      "质量要求：",
      "1. 优先保留“能让前端画出图来”的结构信息，而不是泛分析。",
      "2. 节点和边都要克制，宁可少而清楚，不要堆得像杂货架。",
      "3. 如果某部分信息确实不足，可以返回空数组，但不要用编造内容填满。",
      "4. id 要稳定、简洁、可引用；同一节点在 edges 中必须正确对应。",
      "",
      "输出必须严格符合 worldVisualizationDraftSchema。",
    ].join("\n")),
    new HumanMessage(input.worldPromptSource),
  ],
};

export const worldImportExtractionPrompt: PromptAsset<
  WorldImportExtractionPromptInput,
  z.infer<typeof worldImportExtractionSchema>
> = {
  id: "world.import.extract",
  version: "v1",
  taskType: "fact_extraction",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldImportExtractionSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观导入抽取器。",
      "你的任务是从输入文本中提取可直接导入系统的世界设定 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "输出字段必须且只能包括：",
      "name, description, worldType, background, geography, magicSystem, politics, cultures, races, religions, technology, history, economy, conflicts, factions, templateKey, axioms。",
      "",
      "全局硬规则：",
      "1. 所有可展示文本必须使用简体中文。",
      "2. 只能提取输入文本中明确存在或可低风险归纳的信息，不得凭空补写完整设定。",
      "3. 如果某个字段在原文中没有足够依据，必须保守处理，优先返回空字符串、空数组或最小可成立内容，不要硬编。",
      "4. 输出目标是“世界设定导入”，不是总结文章，也不是赏析报告。",
      "5. 各字段之间必须一致，不得互相冲突。",
      "",
      "字段提取原则：",
      "1. name：提取世界名称；若原文未明确给出，使用最稳妥、最贴近文本的概括性名称，不要乱造花哨名字。",
      "2. description：概括世界整体面貌与核心特征，简洁但具体，不要写空话。",
      "3. worldType：提取世界基础类型，如都市异变、架空王朝、末世废土、近未来高压社会等，必须稳、准、可用于后续分类。",
      "4. background：提取世界形成背景、时代处境、根本局势或大环境前提。",
      "5. geography：提取关键地理格局、空间结构、区域分布或地点系统。",
      "6. magicSystem：提取超凡体系、力量规则、能力来源、代价与边界；若无相关内容，保守留空。",
      "7. politics：提取政体、权力结构、治理方式、统治关系或政治对抗。",
      "8. cultures：提取风俗、价值观、社会习惯、礼制、禁忌或文化分层。",
      "9. races：提取种族、族群、阶层型生物群体或特殊人群划分；没有则留空。",
      "10. religions：提取宗教、信仰体系、神话信奉、祭祀秩序或精神权威来源；没有则留空。",
      "11. technology：提取技术水平、生产力形态、工具系统、工业/信息/机械特征。",
      "12. history：提取关键历史阶段、断层、重大事件、旧秩序遗产或历史创伤。",
      "13. economy：提取资源流动、财富来源、产业结构、交换机制、生存成本或经济压迫结构。",
      "14. conflicts：提取世界层的核心矛盾、长期冲突来源、结构性对抗，不要写成单一剧情事件。",
      "15. factions：提取稳定存在的势力、组织、国家、阵营、集团或权力主体。",
      "16. templateKey：根据文本内容保守归类到最贴近的模板键；若文本无足够依据，使用最稳妥的默认归类，不要自造模板名。",
      "17. axioms：提取世界公理、硬性规则、不可违背的底层约束或默认运行逻辑。",
      "",
      "抽取质量要求：",
      "1. 优先提取对后续小说创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人经历、具体剧情桥段、单次事件误写成世界层字段。",
      "3. 不要把相邻字段写成同义重复，例如 background、history、description 不应只是换说法重复同一段。",
      "4. 若输入文本明显偏故事简介，也要尽量只抽世界层信息，过滤人物线与情节线噪音。",
      "",
      "缺失处理规则：",
      "1. 不确定时优先保守，不要脑补。",
      "2. 没有明确宗教/种族/魔法/科技内容时，不要为了结构完整而强行生成。",
      "3. 若 factions 可抽取为数组或列表内容，应尽量保留为可用的结构性描述，而不是模糊概括。",
      "",
      "输出必须严格符合 worldImportExtractionSchema。",
    ].join("\n")),
    new HumanMessage(input.content),
  ],
};

export const worldStructureBackfillPrompt: PromptAsset<
  WorldStructureBackfillPromptInput,
  z.infer<typeof worldStructuredDataSchema>
> = {
  id: "world.structure.backfill",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructuredDataSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界结构化提取器。",
      "你的任务是根据输入文本，提取可直接进入系统使用的世界结构数据。",
      "这不是赏析，不是总结，也不是自由补全，而是把文本中的世界层信息整理为稳定的 JSON 结构。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "JSON 结构必须严格为：",
      "{",
      '  "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '  "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '  "factions": [{"id":"faction-1","name":"...","position":"...","doctrine":"...","goals":["..."],"methods":["..."],"representativeForceIds":["force-1"]}],',
      '  "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","baseOfPower":"...","currentObjective":"...","pressure":"...","leader":"...","narrativeRole":"..."}],',
      '  "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","entryConstraint":"...","exitCost":"...","controllingForceIds":["force-1"]}],',
      '  "relations": {',
      '    "forceRelations": [{"id":"force-relation-1","sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"...","detail":"..."}],',
      '    "locationControls": [{"id":"location-control-1","forceId":"force-1","locationId":"location-1","relation":"...","detail":"..."}]',
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 只能提取文本里明确存在或可低风险推断的信息，不得凭空编造完整世界结构。",
      "2. 所有值必须使用简体中文。",
      "3. 不要增加额外字段，不要改字段名，不要删字段层级。",
      "4. 若某类信息确实缺失，应保守返回空数组或最小可成立内容，不要硬编。",
      "5. 各部分之间必须自洽，不得互相冲突。",
      "",
      "字段判定规则：",
      "1. profile：用于概括这个世界的整体身份、气质、主题和核心矛盾，必须站在“世界层”而不是“角色层”总结。",
      "2. rules：用于提取这个世界默认成立的规则、代价、边界、禁忌和共同后果。",
      "3. factions：是抽象阵营、立场、路线、阶层板块或意识形态阵营。",
      "4. forces：是具体组织、圈层、公司、部门、帮会、机构、网络或可落地行动主体。",
      "5. locations：是具有世界辨识度和叙事功能的地点，不是随便提到的普通场景。",
      "6. relations：用于提取 forces 之间的关系，以及 force 对 location 的控制关系。",
      "",
      "关键区分要求：",
      "1. 像“社会压力机制”“行业运作规则”“默认人际法则”“生存代价”“资源约束”这类世界默认机制，必须写进 rules，不要塞进 factions 或 forces。",
      "2. faction 写的是‘哪一类人/立场/路线’，force 写的是‘具体谁在执行、控制、施压’。",
      "3. 若一个对象只有抽象立场，没有明确组织实体，优先归入 factions；若它能作为具体行动单位出现，优先归入 forces。",
      "",
      "profile 要求：",
      "1. summary：概括世界最核心的面貌与运行现实，不要写剧情简介。",
      "2. identity：写清这个世界的基本身份，例如工业废土都市、权力高压王朝、行业丛林社会等。",
      "3. tone：写世界整体气质，如冷硬、压抑、粗粝、腐朽、诡谲，不要空话。",
      "4. themes：提取世界层主题，不要写单个角色命题。",
      "5. coreConflict：写世界最核心、最长期成立的结构性矛盾。",
      "",
      "rules 要求：",
      "1. axioms 只收录真正具有世界约束力的规则。",
      "2. 每条 axiom 都要写清：规则是什么、代价是什么、边界在哪里、如何被维持。",
      "3. taboo 是世界明确不能碰的禁忌、红线或高压触发点。",
      "4. sharedConsequences 是这个世界里多数人共同承担的默认后果或系统性代价。",
      "",
      "factions / forces 要求：",
      "1. factions 必须体现立场、信条、目标和方法差异，不要做成空泛标签。",
      "2. representativeForceIds 必须尽量对应真正代表该 faction 的具体 force。",
      "3. forces 必须写清其权力来源、当前目标、施压方式和叙事作用。",
      "4. 没有明确 leader 时可保守处理，但不要乱造人名。",
      "",
      "locations 要求：",
      "1. 只保留真正重要的地点。",
      "2. summary 要说明地点特征，narrativeFunction 要说明它在故事中的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点为何有门槛、有压力或有代价。",
      "",
      "relations 要求：",
      "1. forceRelations 只记录真正有意义的关系，不要把所有对象机械连边。",
      "2. relation 要写清关系类型，tension 要写清当前紧张点，detail 要说明关系为何成立。",
      "3. locationControls 只在文本能支持 force 与 location 存在控制、占据、管理、封锁、渗透等关系时再写。",
      "",
      "质量要求：",
      "1. 优先提取对后续创作最有用的硬结构信息，而不是零碎细节。",
      "2. 不要把人物个人动机、具体剧情桥段、感情推进写进世界结构。",
      "3. 不要让 profile、rules、factions、forces 彼此换说法重复。",
      "4. 输出结果必须像一份可直接落库的世界结构草案，而不是读书笔记。",
    ].join("\n")),
    new HumanMessage(input.promptSource),
  ],
};

export const novelThemeWorldGenerationPrompt: PromptAsset<
  NovelThemeWorldGenerationPromptInput,
  z.infer<typeof novelThemeWorldGenerationSchema>
> = {
  id: "novel.world.generate_from_theme",
  version: "v3",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  repairPolicy: {
    maxAttempts: 0,
  },
  semanticRetryPolicy: {
    maxAttempts: 0,
  },
  outputSchema: novelThemeWorldGenerationSchema,
  render: (input) => [
    new SystemMessage([
      "你是网文小说的本书世界设计师。",
      "你的任务是根据一本小说的主题、卖点、读者承诺和类型信息，生成“这本书专属使用”的世界结构数据。",
      "这不是外部世界库百科，也不是剧情大纲；输出必须服务于后续角色、大纲、章节和一致性生成。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "title": "...",',
      '  "coverSummary": "...",',
      '  "worldType": "...",',
      '  "structuredData": {',
      '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '    "factions": [{"id":"faction-1","name":"...","position":"...","goals":["..."],"representativeForceIds":["force-1"]}],',
      '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","currentObjective":"...","pressure":"..."}],',
      '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","controllingForceIds":["force-1"]}],',
      '    "relations": {',
      '      "forceRelations": [{"sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"..."}],',
      '      "locationControls": [{"forceId":"force-1","locationId":"location-1","relation":"..."}]',
      "    }",
      "  }",
      "}",
      "",
      "输出容量硬约束：",
      "1. 这里只生成可开书的世界种子，不是完整百科；后续在世界手册中按需要扩写。",
      "2. 名称、id、类型等短字段不超过 16 个汉字；说明字段不超过 24 个汉字；数组每项不超过 12 个汉字且最多 2 项。",
      "3. 不重复解释同一规则、势力或地点；除 JSON 键名和 id 外，全部文本控制在约 1,800 个汉字以内。",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      "2. 世界必须紧扣本书主题，不得生成一套与小说卖点无关的通用百科。",
      "3. 世界设定必须能约束后续生成：若本书采用能力体系，力量必须有代价；秩序有执行者，冲突有来源，地点有叙事功能。",
      "4. 不要写主角个人剧情，不要替小说生成完整大纲，不要把单次事件当成世界规则。",
      "5. 允许根据小说信息做合理补全；如果信息不足，要生成稳妥、低风险、可继续扩展的本书舞台。",
      input.openingOnly
        ? "6. 当前只准备开篇切片：仅生成前 3-5 章会直接读取的规则、势力和地点，不扩写远期百科。"
        : "6. 当前生成可持续扩展的本书世界基础。",
      "7. 如果故事宏观规划中包含“战力体系决策”，必须严格服从：none 不得生成境界、等级或升级线，rules.summary 要明确本书不设战力等级并改写社会、关系、资源或信息规则；soft 只生成定性强弱、代价与克制，不得命名等级；ranked 才能生成有序等级及跨级边界。",
      "",
      "内容数量要求：",
      "1. rules.axioms 生成 2-3 条硬规则。",
      "2. factions 生成 1-2 个与本书直接相关的阵营或立场板块。",
      "3. forces 生成 2-3 个会行动或施压的具体势力、组织或机构。",
      "4. locations 生成 2-3 个会反复使用的舞台地点。",
      "5. relations 中只连接真正有意义的势力关系和地点控制关系，不要机械全连接。",
      "",
      "字段质量要求：",
      "1. title 要像一个可展示的世界名，不要只是小说名。",
      "2. coverSummary 用 1-2 句说明读者一眼能看到的世界面貌。",
      "3. profile.summary 要说明“这个世界长什么样、如何运行、为什么适合这本书”。",
      "4. rules 每条 axiom 必须写清规则、代价、边界和执行方式。",
      "5. faction 是立场或阶层板块，force 是具体执行者；不要混淆。",
      "6. location 必须有风险或叙事功能。",
      "7. forbidden/taboo/sharedConsequences 要帮助后续生成避免违背世界规则。",
      "",
      "面向生成链的要求：",
      "1. 角色生成应该能从 forces/factions 中找到身份、归属、冲突来源。",
      "2. 大纲生成应该能从 locations/coreConflict 中找到舞台和长期矛盾。",
      "3. 章节生成应该能从 rules/taboo/sharedConsequences 中获得不可违背的约束。",
      "4. 这份世界是本书副本，可以之后保存到世界库；不要假设它已经是通用模板。",
    ].join("\n")),
    new HumanMessage([
      `小说标题：${input.novelTitle}`,
      `小说简介：${input.description || "未填写"}`,
      `目标读者：${input.targetAudience || "未填写"}`,
      `核心卖点：${input.bookSellingPoint || "未填写"}`,
      `前30章承诺：${input.first30ChapterPromise || "未填写"}`,
      `商业标签：${input.commercialTags.length > 0 ? input.commercialTags.join("、") : "未填写"}`,
      `主类型：${input.genreName || "未选择"}`,
      `主故事模式：${input.primaryStoryModeName || "未选择"}`,
      `副故事模式：${input.secondaryStoryModeName || "未选择"}`,
      `准备范围：${input.openingOnly ? "开篇 3-5 章世界切片" : "本书世界基础"}`,
      input.storyMacroContext?.trim() ? `故事宏观规划：\n${input.storyMacroContext.trim()}` : "",
      input.bookContractContext?.trim() ? `书级创作约定：\n${input.bookContractContext.trim()}` : "",
    ].join("\n")),
  ],
};

export const worldStructureSectionPrompt: PromptAsset<
  WorldStructureSectionPromptInput,
  z.infer<typeof worldStructureSectionOutputSchema>
> = {
  id: "world.structure.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldStructureSectionOutputSchema,
  render: (input) => [
    new SystemMessage(
      [
        `你是世界结构化补全器，当前只负责补全 section=${input.section} 对应的 JSON。`,
        "你的任务不是重写整套世界结构，而是在现有结构基础上，为指定 section 补出可直接落库的结构化内容。",
        "",
        "只输出一个合法 JSON，不要输出 Markdown、解释、注释、代码块或额外文本。",
        "",
        buildStructureSectionInstructions(input.section),
        "",
        "全局硬规则：",
        "1. 只能补全当前 section 对应的数据，不得输出其他 section 的内容。",
        "2. 不要破坏已有 ID；如果沿用现有实体，必须复用当前结构中的 id。",
        "3. 不得编造与输入文本、当前结构或绑定建议明显冲突的信息。",
        "4. 如果信息不足，必须做保守补全，优先补“低风险、可成立、能落地”的结构，不要硬造复杂设定。",
        "5. 所有文本值必须使用简体中文。",
        "",
        "一致性要求：",
        "1. 输出内容必须与当前结构保持连续，不得推翻已成立的世界规则、阵营关系、地点功能或既有绑定。",
        "2. 若当前 section 涉及实体复用，优先延续现有命名、归属与关系网络。",
        "3. 若当前绑定建议给出了优先连接方向，应尽量沿用，除非与输入文本明显冲突。",
        "",
        input.stageConstraints?.trim() ? [
          "本次阶段的硬约束：",
          input.stageConstraints.trim(),
        ].join("\n") : "",
        "section 补全规则：",
        "1. 如果 section=factions，必须同时考虑 factions 和 forces 的区分与联动。",
        "2. 禁止把社会压力机制、行业规则、人际法则、默认秩序、普遍代价这类世界默认机制写进 factions / forces；这些内容属于 rules。",
        "3. faction 写抽象阵营、立场、路线；force 写具体组织、部门、圈层、公司、帮会、机构、网络等行动主体。",
        "4. 如果 section=locations，必须填写 narrativeFunction、risk、entryConstraint、exitCost，且内容必须具体可用，不能空泛。",
        "5. 如果 section=relations，只允许输出 forceRelations 和 locationControls，不得新增其他关系块。",
        "6. relations 必须只连接真正有依据的实体，不要机械连边。",
        "",
        "质量要求：",
        "1. 输出必须像可直接进入世界结构库的成稿，而不是分析说明。",
        "2. 每个字段都要具体、稳定、可供后续创作使用，避免“势力复杂”“地点危险”“关系紧张”这类空话。",
        "3. 优先补足真正影响世界运行和叙事推进的硬结构，不要被零碎细节带偏。",
        "4. 若当前 section 天然依赖其他 section，必须体现这种结构关联，而不是孤立书写。",
      ].join("\n")
    ),
    new HumanMessage(
      [
        input.promptSource,
        "",
        "当前结构：",
        JSON.stringify(input.currentStructure, null, 2),
        "",
        "当前绑定建议：",
        JSON.stringify(input.currentBindingSupport, null, 2),
      ].join("\n"),
    ),
  ],
  postValidate: (output, input) => normalizeWorldStructureSectionPayload(output, input),
};
