import type { WorldReferenceMode } from "@ai-novel/shared/types/worldWizard";
import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../../core/promptTypes";
import { worldReferenceInspirationPayloadSchema } from "../../../../services/world/worldReferenceSchema";
import type {
  WorldInspirationConceptCardLocalizationPromptInput,
  WorldInspirationConceptCardPromptInput,
  WorldPropertyOptionsPromptInput,
  WorldReferenceInspirationPromptInput,
} from "../world.promptTypes";
import {
  worldConceptCardSchema,
  worldPropertyOptionsPayloadSchema,
} from "../world.promptSchemas";

function buildReferenceModeLabel(mode: WorldReferenceMode | null | undefined): string {
  switch (mode) {
    case "extract_base":
      return "提取原作世界基底";
    case "tone_rebuild":
      return "借用原作气质与结构重建";
    case "adapt_world":
    default:
      return "基于原作做架空改造";
  }
}

export const worldReferenceInspirationPrompt: PromptAsset<
  WorldReferenceInspirationPromptInput,
  z.infer<typeof worldReferenceInspirationPayloadSchema>
> = {
  id: "world.reference.inspiration",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldReferenceInspirationPayloadSchema,
  render: (input) => [
    new SystemMessage([
      "你是参考作品世界分析师。",
      "你的任务不是重写一套无关的新故事，而是从参考材料中提炼“可保留的世界基底”与“可用于架空改造的决策边界”，为后续世界观构建提供稳定底板。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "conceptCard": {',
      '    "worldType": "...",',
      '    "templateKey": "custom",',
      '    "coreImagery": ["..."],',
      '    "tone": "...",',
      '    "keywords": ["..."],',
      '    "summary": "..."',
      "  },",
      '  "anchors": [',
      "    {",
      '      "id": "anchor-1",',
      '      "label": "...",',
      '      "content": "..."',
      "    }",
      "  ],",
      '  "seedPackage": {',
      '    "rules": [',
      "      {",
      '        "id": "reference-rule-1",',
      '        "name": "...",',
      '        "summary": "...",',
      '        "cost": "...",',
      '        "boundary": "...",',
      '        "enforcement": "..."',
      "      }",
      "    ],",
      '    "factions": [',
      "      {",
      '        "id": "reference-faction-1",',
      '        "name": "...",',
      '        "position": "...",',
      '        "doctrine": "...",',
      '        "goals": ["..."],',
      '        "methods": ["..."],',
      '        "representativeForceIds": ["reference-force-1"]',
      "      }",
      "    ],",
      '    "forces": [',
      "      {",
      '        "id": "reference-force-1",',
      '        "name": "...",',
      '        "type": "...",',
      '        "factionId": "reference-faction-1",',
      '        "summary": "...",',
      '        "baseOfPower": "...",',
      '        "currentObjective": "...",',
      '        "pressure": "...",',
      '        "leader": "...",',
      '        "narrativeRole": "..."',
      "      }",
      "    ],",
      '    "locations": [',
      "      {",
      '        "id": "reference-location-1",',
      '        "name": "...",',
      '        "terrain": "...",',
      '        "summary": "...",',
      '        "narrativeFunction": "...",',
      '        "risk": "...",',
      '        "entryConstraint": "...",',
      '        "exitCost": "...",',
      '        "controllingForceIds": ["reference-force-1"]',
      "      }",
      "    ]",
      "  }",
      "}",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      '2. conceptCard.templateKey 固定为 "custom"，不得改动。',
      "3. 只能基于参考材料提炼，不得凭空发明大量原文没有支撑的世界结构。",
      "4. 允许做低风险归纳，但禁止把具体剧情桥段、主角感情推进、角色个人动机误写成世界基底。",
      "5. 输出目标是“世界参考资产”，不是剧情梗概，也不是题材改写提案。",
      "",
      "conceptCard 要求：",
      "1. worldType：概括参考世界的基本类型，要稳、准、可复用。",
      "2. coreImagery：提炼最有辨识度的世界意象，优先保留场景感、秩序感、压迫感、行业感或社会质感。",
      "3. tone：概括世界整体气质，如冷硬、压抑、荒诞、粗粝、秩序森严等，不要写空话。",
      "4. keywords：提炼世界层关键词，优先写制度、环境、结构、生态，而不是剧情词。",
      "5. summary：必须说明“哪些应保留、哪些可以改造”，明确这套参考模式真正值得借的世界底板与可变动边界，不能泛泛重写题材。",
      "",
      "anchors 要求：",
      "1. anchors 必须提供 4-6 个，不能少于 4 个，不能多于 6 个。",
      "2. 优先覆盖以下维度中的核心部分：现实基底、城市地点结构、社会压力、行业生态、关系结构、世界边界。",
      "3. 每个 anchor 都必须是“世界层”或“世界-故事接口层”的稳定锚点，能直接影响后续架空改造决策。",
      "4. 不要写具体剧情桥段、具体男女主关系推进、单一角色的私密动机。",
      "5. label 必须简洁清楚，content 必须具体说明这个锚点为何值得保留或如何作为改造基底。",
      "",
      "seedPackage 总规则：",
      "1. seedPackage 用于提取“可直接沿用或轻改的原作世界设定资产”。",
      "2. rules、factions、forces、locations 四类都允许为空数组，但如果材料中有明确可提取内容，应优先保留，不要因为保守而全部清空。",
      "3. 不要为了凑结构胡乱编造；没有依据就留空数组。",
      "4. 优先提取：世界规则、阵营立场、具体组织/势力、地点/场景，这四类可复用内容。",
      "",
      "rules 要求：",
      "1. 只收录真正具有世界约束力的规则、秩序、代价机制或运行逻辑。",
      "2. summary 写规则本身，cost 写遵守/违背/使用该规则的代价，boundary 写适用边界，enforcement 写这条规则如何被维持。",
      "3. 不要把主角个人习惯、剧情偶发事件误写成规则。",
      "",
      "factions 要求：",
      "1. 只提取在世界中有稳定立场、组织性或群体意志的阵营。",
      "2. position 写其在世界格局中的站位，doctrine 写其核心信条或价值倾向。",
      "3. goals 和 methods 必须体现这个阵营如何运作、争夺或施压。",
      "",
      "forces 要求：",
      "1. forces 是更具体、可在故事中落地的组织、部门、团体、权力节点或行动主体。",
      "2. 必须与某个 faction 建立清晰归属，若无清晰归属再保守处理。",
      "3. summary、baseOfPower、currentObjective、pressure、narrativeRole 都要具体，体现其在世界中的可用价值。",
      "",
      "locations 要求：",
      "1. 只提取具有世界辨识度和叙事功能的地点，不要随便抓普通地点名。",
      "2. summary 要说明地点特征，narrativeFunction 要说明其在故事层面的用途。",
      "3. risk、entryConstraint、exitCost 要体现这个地点如何产生限制、代价或压力。",
      "",
      "质量要求：",
      "1. 整体结果必须像“世界参考拆解卡”，而不是随手摘抄的笔记。",
      "2. conceptCard、anchors、seedPackage 三部分必须互相一致，不得彼此打架。",
      "3. 优先保留对后续世界改造最有用的硬结构，不要被零碎细节拖走。",
    ].join("\n")),
    new HumanMessage(input.userPrompt),
  ],
};


export const worldInspirationConceptCardPrompt: PromptAsset<
  WorldInspirationConceptCardPromptInput,
  z.infer<typeof worldConceptCardSchema>
> = {
  id: "world.inspiration.concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观灵感概念卡提炼器。",
      "你的任务是根据输入的灵感文本、世界类型提示和可用素材，提炼出一张可直接用于后续世界观设计的“世界灵感概念卡”。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "所有文本字段都必须使用简体中文。",
      "",
      "输出结构必须严格为：",
      "{",
      '  "worldType":"...",',
      `  "templateKey":"${input.templateKeysText}",`,
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"3-5句中文摘要"',
      "}",
      "",
      "全局硬规则：",
      "1. templateKey 必须从给定可用值中选择，不得自造、改写或留空。",
      "2. 只能基于输入材料提炼，不得凭空发明完整世界设定。",
      "3. 允许做低风险归纳，但禁止把模糊印象写成过强结论。",
      "4. 输出目标是“世界灵感概念卡”，不是剧情梗概，不是人物设定，也不是世界百科。",
      "",
      "字段要求：",
      "1. worldType：",
      "   - 优先结合 worldTypeHint 与灵感文本判断。",
      "   - 应概括世界的基础类型，例如都市现实变体、末世废土、架空王朝、近未来高压社会等。",
      "   - 要稳、准、可用于后续分流，不要写成空泛大词。",
      "",
      "2. templateKey：",
      "   - 必须在给定可用模板中选最贴合的一项。",
      "   - 若输入信息混合度高，也要优先选择最能承载后续展开的主模板。",
      "",
      "3. coreImagery：",
      "   - 提取 3-6 个最有辨识度的世界意象。",
      "   - 优先保留空间感、秩序感、行业感、压迫感、技术感、宗教感、社会质感等“能让人一眼看见这个世界”的意象。",
      "   - 不要写剧情桥段，不要写单个角色动作。",
      "",
      "4. tone：",
      "   - 用一句短语概括这个世界的整体气质，如冷硬压抑、破败混乱、华丽腐朽、克制诡谲等。",
      "   - 不要写成“很精彩”“很有氛围”这种空话。",
      "",
      "5. keywords：",
      "   - 提取 4-8 个关键词。",
      "   - 优先体现世界结构、规则来源、主要压迫、运行逻辑、社会生态或核心气味。",
      "   - 不要和 coreImagery 机械重复。",
      "",
      "6. summary：",
      "   - 必须是 3-5 句中文摘要。",
      "   - 要说明这个世界最值得保留的核心底板是什么、它给人的第一读感是什么、后续适合往什么方向展开。",
      "   - 不要写成剧情简介，不要泛泛复述题材。",
      "",
      "提炼原则：",
      "1. 如果输入是原始灵感，应优先帮用户“收拢方向”，而不是继续发散。",
      "2. 如果输入已经分段提取或带有检索素材，应优先保留其中最稳定、最可复用的世界底板。",
      "3. 如果信息不足，宁可输出更稳的概念卡，也不要硬补复杂设定。",
      "4. 不要把人物关系、具体事件推进、主线冲突误写成世界概念。",
      "",
      "质量要求：",
      "1. 概念卡应让人看完就知道“这是个什么世界、什么气味、后续能往哪走”。",
      "2. 各字段之间必须一致，不能 worldType 是一种世界，tone 和 keywords 却像另一套东西。",
      "3. 结果必须适合进入后续世界观设计流程，而不是停留在灵感随笔层。",
    ].join("\n")),
    new HumanMessage([
      `模式=${input.mode}`,
      `世界类型提示=${input.worldTypeHint}`,
      `灵感文本=${input.promptText}`,
      `是否分段提取=${input.extracted ? "是" : "否"}`,
      `原文长度=${input.originalLength} 字符`,
      `可用世界观素材检索=${input.ragContext || "无"}`,
    ].join("\n")),
  ],
};

export const worldInspirationConceptCardLocalizationPrompt: PromptAsset<
  WorldInspirationConceptCardLocalizationPromptInput,
  z.infer<typeof worldConceptCardSchema>
> = {
  id: "world.inspiration.localize_concept_card",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldConceptCardSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观概念卡本地化编辑。",
      "你的任务是把输入的概念卡内容翻译并润色为自然、准确、可直接展示与继续使用的简体中文版本。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "",
      "必须严格保持原有 JSON 结构不变，输出结构只能是：",
      "{",
      '  "worldType":"...",',
      '  "templateKey":"...",',
      '  "coreImagery":["..."],',
      '  "tone":"...",',
      '  "keywords":["..."],',
      '  "summary":"..."',
      "}",
      "",
      "全局硬规则：",
      "1. 所有可展示文本都必须改写为自然、流畅、准确的简体中文。",
      "2. 必须严格保留原有字段名、字段层级、数组长度和基本语义，不得新增、删除、重命名字段。",
      "3. templateKey 属于结构字段，必须保持原样，不得翻译、改写或替换。",
      "4. 不得改变概念卡原本的世界类型判断、意象方向、气质定位和关键词含义。",
      "5. 不得补写新的世界设定、剧情信息或解释性内容。",
      "",
      "本地化要求：",
      "1. 不是机械直译，而是要转写成符合中文世界观策划语境的自然表达。",
      "2. 若原文存在明显生硬、重复、翻译腔或英文思维表达，应在不改变原意的前提下润色。",
      "3. coreImagery 和 keywords 应保持短词或短语风格，简洁、有辨识度，不要扩写成长句。",
      "4. tone 应像中文策划中真实会使用的气质描述，不要翻得僵硬。",
      "5. summary 应保持概念卡摘要风格，清楚、凝练，不要写成散文或说明书。",
      "",
      "质量要求：",
      "1. 输出结果应像一张成熟的中文世界灵感概念卡，而不是翻译稿。",
      "2. 各字段之间必须一致，不得出现 worldType 是一种世界、tone 和 keywords 却像另一种世界的情况。",
      "3. 若输入中已有中文且表达自然，应尽量保留，不要为了“翻译”而硬改。",
      "",
      "输出必须严格符合 worldConceptCardSchema。",
    ].join("\n")),
    new HumanMessage(input.conceptCardJson),
  ],
};

export const worldPropertyOptionsPrompt: PromptAsset<
  WorldPropertyOptionsPromptInput,
  z.infer<typeof worldPropertyOptionsPayloadSchema>
> = {
  id: "world.property_options.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldPropertyOptionsPayloadSchema,
  render: (input) => {
    const isReferenceMode = Boolean(input.referenceMode);

    return [
      new SystemMessage(
        isReferenceMode
          ? [
              "你是参考作品架空改造规划师。",
              "你的任务不是重写一套无关的新世界，而是基于参考作品的世界锚点、保留要求和改造边界，提炼出“正式生成世界前必须先决定”的关键世界决策项。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策",',
              '      "choices": [',
              "        {",
              '          "id": "choice-a",',
              '          "label": "方向 A",',
              '          "summary": "说明这个方向如何改造原作世界"',
              "        }",
              "      ]",
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 每个 option 都必须包含 2-4 个 choices。",
              "5. choices 必须是互斥分支，而不是同义改写、强弱版本或描述角度变化。",
              "6. 不要生成角色动机、感情推进、具体桥段、单章冲突这类故事层选项。",
              "7. 只能围绕“世界层”或“世界-故事接口层”做决策设计。",
              "",
              "决策项要求：",
              "1. 每个 option 都必须是真正会改变后续世界构建方向的前置决策，而不是伪选项。",
              "2. name 必须简洁、清楚、可直接给用户点选，不要写成长句。",
              "3. description 必须说明“这个属性决定什么”以及“为什么要现在先决定”，不能空泛。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能重复 description。",
              "",
              "choices 设计规则：",
              "1. 每个 choice 都必须代表一条清晰可分叉的架空改造路线。",
              "2. choices 之间要体现真正不同的世界走法，例如现实保留程度、秩序显隐方式、压迫结构来源、规则公开程度、地点系统组织方式等。",
              "3. 不要输出只是措辞不同的近义分支。",
              "4. summary 必须说明“这一分支会如何改造原作世界”，并点出边界与代价感。",
              "",
              "参考改造原则：",
              "1. 决策项必须围绕参考作品的世界基底展开，而不是借壳起一套无关新世界。",
              "2. 优先保留真正定义原作气质的底层结构，再在可改造边界内做分叉设计。",
              "3. 如果某个方向会让原作核心气质失真，应在该 choice.summary 中体现这种边界。",
              "4. 优先考虑现实基底、城市规则、社会压迫结构、地点系统、势力网络、公开与隐秘边界这类真正影响世界的核心轴。",
              "",
              "质量要求：",
              "1. options 之间尽量覆盖不同 targetLayer，不要全部挤在同一层。",
              "2. 每个 option 都应让用户一眼明白“我到底在决定哪个世界轴”。",
              "3. 输出结果应直接服务于下一步世界生成，而不是停留在概念讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
          : [
              "你是小说世界生成器的前置决策规划师。",
              "你的任务是在正式生成世界之前，先提炼出一组真正值得用户先做决定的“关键世界属性选项”。",
              "这些选项不是装饰性问题，而是会直接影响后续世界构建方向的前置决策轴。",
              "",
              "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
              "输出结构必须严格为：",
              "{",
              '  "options": [',
              "    {",
              '      "id": "可选",',
              '      "name": "属性名称",',
              '      "description": "40-90字，说明这个属性决定什么，以及为什么值得在生成前就做选择",',
              '      "targetLayer": "foundation|power|society|culture|history|conflict",',
              '      "reason": "一句话说明它为什么值得优先决策"',
              "    }",
              "  ]",
              "}",
              "",
              "全局硬规则：",
              "1. options 数量必须与要求数量完全一致。",
              "2. 所有文本必须使用简体中文。",
              "3. targetLayer 只能是：foundation、power、society、culture、history、conflict。",
              "4. 不要生成“世界名称”“世界简介”“整体风格”这类过于宽泛或无实际选择价值的伪选项。",
              "",
              "属性设计要求：",
              "1. 每个 option 都必须是具体、可选择、会影响后续世界搭建方向的关键属性。",
              "2. name 必须简洁明确，让用户一眼知道自己在决定什么。",
              "3. description 必须说明：这个属性具体控制世界的哪一部分，以及为什么值得在生成前优先确定。",
              "4. reason 必须一句话点明它为何属于优先决策项，不能和 description 同义重复。",
              "",
              "生成原则：",
              "1. 这些选项应延续“先选属性、再补细节”的思路，优先抓真正影响世界成型方向的分歧点。",
              "2. 属性之间尽量独立，但组合后应能自然拼成一套连贯世界。",
              "3. 优先考虑基础层、力量层、社会层、文化层、历史层、冲突层，不要全部堆在一个层面。",
              "4. 可以参考经典网文世界搭建逻辑，但不要落入陈词滥调，要保留辨识度。",
              "5. 必须结合世界类型、模板说明、概念摘要、核心意象、关键词、基调和用户原始灵感综合判断。",
              "",
              "质量要求：",
              "1. 每个属性都应让用户看完后能自然做选择，而不是还要再解释一遍。",
              "2. 不要输出空泛大词，例如“世界复杂度”“设定深度”“故事张力”。",
              "3. 输出结果应直接服务下一步世界生成，而不是停留在灵感讨论层。",
              input.retryStrict
                ? "4. 本次必须严格返回 JSON；如果不确定，也要先给出结构化 options，不得省略。"
                : "",
            ].filter(Boolean).join("\n")
      ),
      new HumanMessage(
        isReferenceMode
          ? [
              `参考方式：${buildReferenceModeLabel(input.referenceMode)}`,
              input.referenceAnchors && input.referenceAnchors.length > 0
                ? `原作世界锚点：\n${input.referenceAnchors.map((item) => `- ${item.label}：${item.content}`).join("\n")}`
                : "",
              input.preserveElements && input.preserveElements.length > 0
                ? `必须保留：${input.preserveElements.join("、")}`
                : "",
              input.allowedChanges && input.allowedChanges.length > 0
                ? `允许改造：${input.allowedChanges.join("、")}`
                : "",
              input.forbiddenElements && input.forbiddenElements.length > 0
                ? `禁止偏离：${input.forbiddenElements.join("、")}`
                : "",
              `请生成 ${input.optionsCount} 个“架空改造前必须先决定”的关键世界决策项。`,
              "补充要求：",
              "1. 每个决策项都必须是世界层或世界-故事接口层的改造轴。",
              "2. 每个决策项都必须给出 2-4 个互斥分支 choices，让用户能真正做路线选择。",
              "3. choices 之间必须体现不同架空方向，而不是描述角度变化。",
              "4. 不要偏离原作世界基底去重新发明无关新世界。",
            ].filter(Boolean).join("\n")
          : [
              `世界类型：${input.worldType}`,
              `模板：${input.templateName}`,
              `模板说明：${input.templateDescription}`,
              input.classicElements.length > 0 ? `可参考的经典元素：${input.classicElements.join("、")}` : "",
              input.pitfalls.length > 0 ? `需要避开的常见坑点：${input.pitfalls.join("、")}` : "",
              `世界概念摘要：${input.conceptSummary}`,
              input.coreImagery.length > 0 ? `核心意象：${input.coreImagery.join("、")}` : "",
              input.keywords.length > 0 ? `关键词：${input.keywords.join("、")}` : "",
              input.tone.trim() ? `整体基调：${input.tone.trim()}` : "",
              input.sourcePrompt.trim() ? `用户原始灵感：${input.sourcePrompt.trim()}` : "",
              input.ragContext?.trim() ? `可参考素材：${input.ragContext.trim()}` : "",
              `请生成 ${input.optionsCount} 个“适合在正式生成世界前先做决定”的关键世界属性选项。`,
              "补充要求：",
              "1. 优先覆盖真正重要的世界分歧点，而不是宽泛项。",
              "2. 属性之间尽量分布到不同层级，组合后能形成完整世界。",
              "3. 每个属性都要让用户一眼明白自己在决定什么。",
            ].filter(Boolean).join("\n")
      ),
    ];
  },
};
