import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../../core/promptTypes";
import type { NovelThemeWorldGenerationPromptInput } from "../world.promptTypes";
import { novelThemeWorldGenerationSchema } from "../world.promptSchemas";

export const novelThemeWorldGenerationPrompt: PromptAsset<
  NovelThemeWorldGenerationPromptInput,
  z.infer<typeof novelThemeWorldGenerationSchema>
> = {
  id: "novel.world.generate_from_theme",
  version: "v3",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  repairPolicy: {
    maxAttempts: 0,
  },
  semanticRetryPolicy: {
    maxAttempts: 0,
  },
  outputSchema: novelThemeWorldGenerationSchema,
  render: (input) => [
    new SystemMessage([
      "你是网文小说的本书世界设计师。",
      "你的任务是根据一本小说的主题、卖点、读者承诺和类型信息，生成“这本书专属使用”的世界结构数据。",
      "这不是外部世界库百科，也不是剧情大纲；输出必须服务于后续角色、大纲、章节和一致性生成。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "title": "...",',
      '  "coverSummary": "...",',
      '  "worldType": "...",',
      '  "structuredData": {',
      '    "profile": {"summary":"...","identity":"...","tone":"...","themes":["..."],"coreConflict":"..."},',
      '    "rules": {"summary":"...","axioms":[{"id":"rule-1","name":"...","summary":"...","cost":"...","boundary":"...","enforcement":"..."}],"taboo":["..."],"sharedConsequences":["..."]},',
      '    "factions": [{"id":"faction-1","name":"...","position":"...","goals":["..."],"representativeForceIds":["force-1"]}],',
      '    "forces": [{"id":"force-1","name":"...","type":"...","factionId":"faction-1","summary":"...","currentObjective":"...","pressure":"..."}],',
      '    "locations": [{"id":"location-1","name":"...","terrain":"...","summary":"...","narrativeFunction":"...","risk":"...","controllingForceIds":["force-1"]}],',
      '    "relations": {',
      '      "forceRelations": [{"sourceForceId":"force-1","targetForceId":"force-2","relation":"...","tension":"..."}],',
      '      "locationControls": [{"forceId":"force-1","locationId":"location-1","relation":"..."}]',
      "    }",
      "  }",
      "}",
      "",
      "输出容量硬约束：",
      "1. 这里只生成可开书的世界种子，不是完整百科；后续在世界手册中按需要扩写。",
      "2. 名称、id、类型等短字段不超过 16 个汉字；说明字段不超过 24 个汉字；数组每项不超过 12 个汉字且最多 2 项。",
      "3. 不重复解释同一规则、势力或地点；除 JSON 键名和 id 外，全部文本控制在约 1,800 个汉字以内。",
      "",
      "全局硬规则：",
      "1. 所有文本必须使用简体中文。",
      "2. 世界必须紧扣本书主题，不得生成一套与小说卖点无关的通用百科。",
      "3. 世界设定必须能约束后续生成：若本书采用能力体系，力量必须有代价；秩序有执行者，冲突有来源，地点有叙事功能。",
      "4. 不要写主角个人剧情，不要替小说生成完整大纲，不要把单次事件当成世界规则。",
      "5. 允许根据小说信息做合理补全；如果信息不足，要生成稳妥、低风险、可继续扩展的本书舞台。",
      input.openingOnly
        ? "6. 当前只准备开篇切片：仅生成前 3-5 章会直接读取的规则、势力和地点，不扩写远期百科。"
        : "6. 当前生成可持续扩展的本书世界基础。",
      "7. 如果故事宏观规划中包含“战力体系决策”，必须严格服从：none 不得生成境界、等级或升级线，rules.summary 要明确本书不设战力等级并改写社会、关系、资源或信息规则；soft 只生成定性强弱、代价与克制，不得命名等级；ranked 才能生成有序等级及跨级边界。",
      "",
      "内容数量要求：",
      "1. rules.axioms 生成 2-3 条硬规则。",
      "2. factions 生成 1-2 个与本书直接相关的阵营或立场板块。",
      "3. forces 生成 2-3 个会行动或施压的具体势力、组织或机构。",
      "4. locations 生成 2-3 个会反复使用的舞台地点。",
      "5. relations 中只连接真正有意义的势力关系和地点控制关系，不要机械全连接。",
      "",
      "字段质量要求：",
      "1. title 要像一个可展示的世界名，不要只是小说名。",
      "2. coverSummary 用 1-2 句说明读者一眼能看到的世界面貌。",
      "3. profile.summary 要说明“这个世界长什么样、如何运行、为什么适合这本书”。",
      "4. rules 每条 axiom 必须写清规则、代价、边界和执行方式。",
      "5. faction 是立场或阶层板块，force 是具体执行者；不要混淆。",
      "6. location 必须有风险或叙事功能。",
      "7. forbidden/taboo/sharedConsequences 要帮助后续生成避免违背世界规则。",
      "",
      "面向生成链的要求：",
      "1. 角色生成应该能从 forces/factions 中找到身份、归属、冲突来源。",
      "2. 大纲生成应该能从 locations/coreConflict 中找到舞台和长期矛盾。",
      "3. 章节生成应该能从 rules/taboo/sharedConsequences 中获得不可违背的约束。",
      "4. 这份世界是本书副本，可以之后保存到世界库；不要假设它已经是通用模板。",
    ].join("\n")),
    new HumanMessage([
      `小说标题：${input.novelTitle}`,
      `小说简介：${input.description || "未填写"}`,
      `目标读者：${input.targetAudience || "未填写"}`,
      `核心卖点：${input.bookSellingPoint || "未填写"}`,
      `前30章承诺：${input.first30ChapterPromise || "未填写"}`,
      `商业标签：${input.commercialTags.length > 0 ? input.commercialTags.join("、") : "未填写"}`,
      `主类型：${input.genreName || "未选择"}`,
      `主故事模式：${input.primaryStoryModeName || "未选择"}`,
      `副故事模式：${input.secondaryStoryModeName || "未选择"}`,
      `准备范围：${input.openingOnly ? "开篇 3-5 章世界切片" : "本书世界基础"}`,
      input.storyMacroContext?.trim() ? `故事宏观规划：\n${input.storyMacroContext.trim()}` : "",
      input.bookContractContext?.trim() ? `书级创作约定：\n${input.bookContractContext.trim()}` : "",
    ].join("\n")),
  ],
};
