import { HumanMessage, SystemMessage } from "@langchain/core/messages";
import { z } from "zod";
import type { PromptAsset } from "../../../core/promptTypes";
import { worldVisualizationDraftSchema } from "../../../../services/world/worldVisualizationSchema";
import type { WorldVisualizationPromptInput } from "../world.promptTypes";

export const worldVisualizationPrompt: PromptAsset<
  WorldVisualizationPromptInput,
  z.infer<typeof worldVisualizationDraftSchema>
> = {
  id: "world.visualization.generate",
  version: "v1",
  taskType: "planner",
  mode: "structured",
  language: "zh",
  contextPolicy: {
    maxTokensBudget: 0,
  },
  outputSchema: worldVisualizationDraftSchema,
  render: (input) => [
    new SystemMessage([
      "你是世界观可视化抽取器。",
      "你的任务是把输入中的世界设定、阵营关系、地理结构和时间演变，提炼为可直接用于可视化展示的结构化 JSON。",
      "",
      "只输出一个合法 JSON 对象，不要输出 Markdown、解释、注释、代码块或额外文本。",
      "输出结构必须严格为：",
      "{",
      '  "factionGraph": {',
      '    "nodes": [{"id":"faction-1","label":"...","type":"state|faction|race|organization|other"}],',
      '    "edges": [{"source":"faction-1","target":"faction-2","relation":"同盟|合作|支援|对抗|敌对|统属|压制|贸易|竞争|中立|关联"}]',
      "  },",
      '  "powerTree": [{"level":"L1","description":"..."}],',
      '  "geographyMap": {',
      '    "nodes": [{"id":"geo-1","label":"...","x":50,"y":50,"directionHint":"north|south|east|west|center|northeast|northwest|southeast|southwest","regionType":"continent|country|region|city|landmark|border|route|other","terrain":"...","summary":"...","parentId":null,"controllingForceIds":["faction-1"],"risk":"...","storyRelevance":"..."}],',
      '    "edges": [{"source":"geo-1","target":"geo-2","relation":"相邻|通道|隔绝|控制","routeType":"road|river|sea|portal|trade|military|border|other","distanceHint":"...","direction":"north|south|east|west|center|northeast|northwest|southeast|southwest","risk":"..."}]',
      "  },",
      '  "timeline": [{"year":"...","event":"..."}]',
      "}",
      "",
      "全局硬规则：",
      "1. 所有 label、relation、description、event、year 都必须使用简体中文。",
      "2. 只能抽取文本中明确存在或可低风险推断的信息，不得凭空编造世界结构。",
      "3. 输出目标是“可视化结构抽取”，不是世界观赏析，也不是剧情总结。",
      "4. 各部分之间必须一致，不得出现 factionGraph、geographyMap、timeline 互相打架的情况。",
      "",
      "factionGraph 规则：",
      "1. 必须优先反映真实势力关系，不要用模糊泛化关系替代明确关系。",
      "2. nodes 数量控制在 4-12 个之间，优先保留核心势力、关键种族、主要组织或国家主体。",
      "3. type 只能使用：state、faction、race、organization、other。",
      "4. edge.relation 只能使用：同盟、合作、支援、对抗、敌对、统属、压制、贸易、竞争、中立、关联。",
      "5. 不要为了凑节点而加入无叙事价值的小势力或一次性提及对象。",
      "6. 如果两个势力关系不明确，就不要强行连边。",
      "",
      "powerTree 规则：",
      "1. powerTree 用于抽取权力层级、力量阶梯、统治结构或资源支配结构。",
      "2. 每项 level 应体现层级位置，如 L1、L2、L3。",
      "3. description 必须写清这一层代表什么权力/力量层，而不是空泛写“上层”“中层”。",
      "4. 若文本没有明确力量层级，可保守提炼最稳定的层级结构，不要硬造复杂等级体系。",
      "",
      "geographyMap 规则：",
      "1. geographyMap 用于提取关键地点之间的空间位置与连通关系，而不是列地点清单。",
      "2. nodes 应优先保留对世界运行、势力分布或故事推进有意义的核心地点。",
      "3. x/y 使用 0-100 的相对地图坐标：x 越大越偏东，y 越大越偏南；中心地点约为 50/50。",
      "4. directionHint 必须与 x/y 大体一致；文本没有明确方向时，允许根据叙事层级做保守布局，但不要假装有精确距离。",
      "5. regionType 用于区分大陆、国家、区域、城市、地标、边境、路线或其他。",
      "6. edges.relation 只能使用：相邻、通道、隔绝、控制。",
      "7. routeType 用于标记道路、河流、海路、传送、商道、军道、边界或其他；没有依据时用 other。",
      "8. 不要把纯剧情场景、一次性地点或无空间结构价值的地点塞进地图。",
      "9. 若地点之间关系不明确，不要强行连边。",
      "",
      "timeline 规则：",
      "1. timeline 只提取对世界格局有影响的重要历史节点、阶段变化或关键事件。",
      "2. year 可以是具体年份，也可以是阶段性时间表达，如“旧纪元末期”“三年前”“新朝建立初期”。",
      "3. event 必须简洁写清“发生了什么变化”，不要写成长段故事。",
      "4. 不要把普通背景介绍或局部人物经历误写成世界时间线节点。",
      "",
      "质量要求：",
      "1. 优先保留“能让前端画出图来”的结构信息，而不是泛分析。",
      "2. 节点和边都要克制，宁可少而清楚，不要堆得像杂货架。",
      "3. 如果某部分信息确实不足，可以返回空数组，但不要用编造内容填满。",
      "4. id 要稳定、简洁、可引用；同一节点在 edges 中必须正确对应。",
      "",
      "输出必须严格符合 worldVisualizationDraftSchema。",
    ].join("\n")),
    new HumanMessage(input.worldPromptSource),
  ],
};
